import type { Metadata } from 'next'
import '@/styles/globals.css'
import QueryClientWrapper from './QueryClientProvider'
import { ThemeProvider } from '@/components/theme-provider'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className='bg-background antialiased dark:bg-background-dark'>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
          <QueryClientWrapper>
            {children}
            <ToastContainer autoClose={2000} />
          </QueryClientWrapper>
        </ThemeProvider>
      </body>
    </html>
  )
}
